### ISSUE TITLE
about motion brach

### ISSUE THREAD

**Issue by frensher** [ctrasd/LagrangeGait#4]
你好
![图片](https://user-images.githubusercontent.com/42425485/178912874-85f6ee8f-4d93-4287-ae8c-00de6dc12214.png)
就是截图这块,我完全没有看懂.
前后两帧图片计算个相似度,然后二值采样降低计算量嘛
x'和x的偏移公式,f1是什么意思?感觉这个公式好突兀,跟后面联系不起来啊
能简单解释下吗

**Comment by ctrasd** [comment]
See question #3
